language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- git submodule update --init --recursive
env:
  global:
  - secure: B2mzi+nNVwssSi09wpybyDTLV/2z3anK7DhL8pqoVZsWLOiXJYn+XZPWW7vv/jG3L2gLC5qp6+d2ahIHy/R8V4BVxx0z6jm0U1f/ciCiuJ9sPwb8Ha3b4rjYt8qNCE5Yd6dyuzDqmlkNbEhNyC7QyYf4GNsz/Qhk/cqQYqZQyog=
  - secure: ZI7rGeIFai1HGVQqCmsRtmZQb1of2cHaJqic4Y8F+EEo6DChOF2bIlQkQtjrYNtKD4y4iZAL0FQt+kzeJKLQMOgwg+dCb4lgrF534MRXoRvNSjMGKfj/loYuLxrEYLBkodKPs60ZvlRov01KCulNUdVzqhDq0c7B+n/bAER2jBo=
